cmake_minimum_required(VERSION 3.28)
project(1)

set(CMAKE_CXX_STANDARD 17)
add_executable(lab1 Lab1/lab1.cpp)
add_executable(lab1_1 Lab1/lab1_1.cpp)
add_executable(lab2 Lab2/lab2.cpp)
add_executable(lab2_2 Lab2/lab2_2.cpp)
add_executable(lab2_3 Lab2/lab2_3.cpp)
add_executable(lab3 Lab3/main.cpp Lab3/Pool.cpp Lab3/Pool.h)
add_executable(server Lab4/server.cpp)
add_executable(client Lab4/client.cpp)
target_link_libraries(server ws2_32)
target_link_libraries(client ws2_32)
add_executable(serverHTTP Lab5/serverHTTP.cpp)
target_link_libraries(serverHTTP ws2_32)